global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s

scrape_configs:
  - job_name: travel-planner-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000
